# VoiceVox-Engineに関する設定
voicevox:
    # VoiceVox-EngineがホストしているURL
    api: 'http://localhost:50021'
    # 読み上げに使用するデフォルトのSpeakerID
    defaultSpeaker: 1

# DiscordBotに関する設定
bot:
    # Bot接続に使用するToken
    token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    # 管理用サーバーID(いくつかの管理用コマンドが使用できるようになります)
    ownerGuild: 'xxxxxxxxxxxxx'
    # Botが接続できるサーバーの最大値
    maxSession: 16
    # ユーザーデータの保存パス
    userDataPath: 'data/data.json'

# デバッグ情報を表示するか
debug: false
